
version: "3.8"
services:
  postgres:
    image: postgres:15.1
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/data/postgres
    restart: unless-stopped

  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - ./redis:/var/lib/redis
      - ./redis/redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    ports:
      - 8081:8081
    depends_on:
      - redis
  # pgadmin:
  #   image: dpage/pgadmin4:6.18
  #   networks:
  #     - postgres
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./data/pgadmin:/root/.pgadmin
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
  #     - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
  #   restart: unless-stopped
  
  # nestjs-api:
  #   build: 
  #     context: .
  #     target: production
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - postgres